In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('./CSVFiles/FullData.csv')

In [11]:
df.shape

(36259, 492)

In [4]:
df.head()

,SEQN,depression,gender,age,race,citizenship,education_level,marital_status,household_size,pregnant,...,Rx_INSULIN REGULAR,Rx_days_INSULIN REGULAR,Rx_MEMANTINE,Rx_days_MEMANTINE,Rx_DIPHENHYDRAMINE,Rx_days_DIPHENHYDRAMINE,Rx_MINOCYCLINE,Rx_days_MINOCYCLINE,Rx_METHOCARBAMOL,Rx_days_METHOCARBAMOL
0,31131,Not Depressed,1,44,Black,Citizen,4,Married,4,No,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1,31132,Not Depressed,0,70,White,Citizen,5,Married,2,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,31134,Not Depressed,0,73,White,Citizen,3,Married,2,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
3,31139,Not Depressed,1,18,Other Hispanic,Citizen,0,Never Married,3,No,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,31143,Not Depressed,0,19,White,Citizen,0,Never Married,3,Missing,...,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

In [9]:
df.describe()

,SEQN,gender,age,education_level,household_size,household_income,asthma,asthma_onset,asthma_currently,asthma_emergency,...,Rx_INSULIN REGULAR,Rx_days_INSULIN REGULAR,Rx_MEMANTINE,Rx_days_MEMANTINE,Rx_DIPHENHYDRAMINE,Rx_days_DIPHENHYDRAMINE,Rx_MINOCYCLINE,Rx_days_MINOCYCLINE,Rx_METHOCARBAMOL,Rx_days_METHOCARBAMOL
count,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,...,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000,36259.000000
mean,67521.563805,0.508756,47.786260,3.209107,3.206349,6.919358,0.147743,3.142365,0.085965,0.013762,...,0.002399,7.007750,0.001544,1.318266,0.001462,2.010122,0.001517,1.481811,0.002565,3.059378
std,20832.294029,0.499930,18.763978,1.464932,1.677450,3.523153,0.354850,10.763107,0.280316,0.116504,...,0.048926,202.190034,0.039270,50.759714,0.038205,89.828461,0.038918,66.760627,0.050580,109.116624
min,31131.000000,0.000000,18.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,49463.000000,0.000000,31.000000,2.000000,2.000000,4.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,66902.000000,1.000000,47.000000,3.000000,3.000000,7.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,85901.500000,1.000000,63.000000,4.000000,4.000000,10.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,102956.000000,1.000000,85.000000,5.000000,7.000000,12.000000,1.000000,85.000000,1.000000,1.000000,...,1.000000,14600.000000,1.000000,3650.000000,1.000000,8760.000000,1.000000,7300.000000,1.000000,8760.000000

In [12]:
df.columns

Index(['SEQN', 'depression', 'gender', 'age', 'race', 'citizenship',
       'education_level', 'marital_status', 'household_size', 'pregnant',
       ...
       'Rx_INSULIN REGULAR', 'Rx_days_INSULIN REGULAR', 'Rx_MEMANTINE',
       'Rx_days_MEMANTINE', 'Rx_DIPHENHYDRAMINE', 'Rx_days_DIPHENHYDRAMINE',
       'Rx_MINOCYCLINE', 'Rx_days_MINOCYCLINE', 'Rx_METHOCARBAMOL',
       'Rx_days_METHOCARBAMOL'],
      dtype='object', length=492)